### ISSUE TITLE
Remove h2 titles

### ISSUE THREAD

**Issue by ai** [zelark/nano-id-cc#1]
Right now code example is not visible on standard screen (my screen is even bigger).

https://i.imgur.com/MehW8iM.png

But if we will remove `Description` and `Calculator` titles, we will not lose information (since it is obvious) but will save vertical size. Also, we can remove `Code sample` as well.

https://i.imgur.com/3ksr1q4.png

**Comment by zelark** [comment]
Yeah, I agree with that. Thanks for a fresh view. There was no headers initially, but at some point I added it to emphasize the structure. Now it does seem redundant. I'll remove it soon.
