### ISSUE TITLE
Make logo clickable

### ISSUE THREAD

**Issue by ai** [zelark/nano-id-cc#10]
I think we could put a link to Nano ID repo to the logo on website

The original issue is https://github.com/ai/nanoid/issues/74.

**Comment by zelark** [comment]
Definitely.

**Comment by zelark** [comment]
Hey @hrithik-jha, are you still going to do this?

**Comment by hrithik-jha** [comment]
I can but wanted to ask if we can make changes in the other repo

**Comment by zelark** [comment]
What repo do you mean?

**Comment by hrithik-jha** [comment]
@zelark Sorry, got confused about the repo. Anyways I have created a PR https://github.com/zelark/nano-id-cc/pull/11 to add the feature.

**Comment by zelark** [comment]
@hrithik-jha thank you. It needs a little fix.
