### ISSUE TITLE
Reduce max ID length in slider

### ISSUE THREAD

**Issue by ai** [zelark/nano-id-cc#2]
The current slider has values from 2 to 128. But I can’t find a case when you need more than 32 symbols in ID.

**Comment by zelark** [comment]
A hypothetical case I would imagine when their alphabet is binary and they generate 10000 IDs per hour.

**Comment by zelark** [comment]
The other case about those guys who are just curious.

Let's stop at least at 36 characters, it won't overflow the code block and will give a little bit more room to play.

**Comment by zelark** [comment]
Also, I think it's a good idea to get focus on a slider by default.
