### ISSUE TITLE
Escape <> in the example

### ISSUE THREAD

**Issue by notpushkin** [zelark/nano-id-cc#22]
Right now they are interpreted as is which can lead to weird results:
![image](https://user-images.githubusercontent.com/1298948/73286933-7b5c3200-4209-11ea-993c-2bbab6ef30fd.png)
![image](https://user-images.githubusercontent.com/1298948/73286981-8e6f0200-4209-11ea-8b93-196fca66bb6a.png)

**Comment by zelark** [comment]
Hi, @notpushkin. Good catch!
Do you want to open a PR?

**Comment by notpushkin** [comment]
I have very little experience with Clojure but let's try!
