### ISSUE TITLE
difference in 60 ids/hr vs 1 id/sec

### ISSUE THREAD

**Issue by xerosanyam** [zelark/nano-id-cc#26]
hey, I am trying to understand why the demo gives a different number for mathematically, the same input
ie. 60 ids/hr = 1 id/sec

## 60 ids/hr = ~26 days
![image](https://user-images.githubusercontent.com/3167278/86794757-7c33a280-c08a-11ea-98ff-425d896cf9b6.png)

## 1 id/s = ~10 hrs
![image](https://user-images.githubusercontent.com/3167278/86794793-85bd0a80-c08a-11ea-9a4d-2a176656bf62.png)

**Comment by zelark** [comment]
Hi @xerosanyam. There is a wrong point in the comparison. It should be 3600 IDs per hour, not 60.

**Comment by xerosanyam** [comment]
oops, my bad! 😓
