### ISSUE TITLE
Calculator for absolute number of IDs?

### ISSUE THREAD

**Issue by borekb** [zelark/nano-id-cc#32]
I'd like to answer the question "how many rows there would need to be in our database for nanoid to have a 1% probability of producing an already existing ID". Just maybe an idea for this awesome calculator (I like the current approach, just think that maybe there could be an additional "view" on the probability).

**Comment by zelark** [comment]
Oh, I man, sorry I didn't answer you. I think I can thinking about it on my upcoming vacation.

**Comment by KaKi87** [comment]
Hello,
Any news on this ?
Thanks

**Comment by zelark** [comment]
@KaKi87 thanks for kicking up this issue. I don't have time to work on this, however it seems like it won't take much. Is it ok if I format the number with `Intl.NumberFormat('en', { notation: 'compact' })`? A full number might take a lot of space, and it won't be human readable.

So the result will look like
<img width="739" alt="image" src="https://github.com/zelark/nano-id-cc/assets/2854582/dd61ff95-7548-4882-97d0-d3b41e327f3a">

**Comment by KaKi87** [comment]
That looks nice, thanks.

**Comment by KaKi87** [comment]
So, from the beginning, you already had the answer in the `critical-number` variable ? :o

**Comment by zelark** [comment]
> So, from the beginning, you already had the answer in the `critical-number` variable ? :o

Yep! ^_^

**Comment by borekb** [comment]
This is fantastic, thanks a lot! ❤️
