### ISSUE TITLE
The results are different between `zelark` version and `alex7kom` version

### ISSUE THREAD

**Issue by bhuynhdev** [zelark/nano-id-cc#33]
Input:

* Alphatbet: `0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz`
* Length: 20
* Rate: 10000 Ids per Second

[`alex7kom` version](https://alex7kom.github.io/nano-nanoid-cc/?alphabet=0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz&size=20&speed=10000&speedUnit=second) -> `~376 thousands of years of work are needed in order to have a 1% probability of at least one collision.`

![image](https://user-images.githubusercontent.com/55563202/126814999-fb66e856-4dd4-4b26-a693-ee7cc3e464d6.png)

`zelark` version: `~1 billion years needed, in order to have a 1% probability of at least one collision.`
![image](https://user-images.githubusercontent.com/55563202/126815096-a505c7d8-92f0-4353-8bdb-ae8726bd41af.png)

Why is the difference ? Which is the correct one ?

**Comment by zelark** [comment]
Because in the first case the unit is `second`, and in the second case `hour`.
