### ISSUE TITLE
Copy-to-clipboard button

### ISSUE THREAD

**Issue by zelark** [zelark/nano-id-cc#4]
It's nice to have such button, especially on mobile platforms.

**Comment by hrithik-jha** [comment]
I'd like to try this one too if that's fine.

**Comment by zelark** [comment]
Cool! It's yours.

**Comment by hrithik-jha** [comment]
Sorry for being inactive for a week, I'll try this as soon as I can

**Comment by hrithik-jha** [comment]
So the front-end is ready, what do you suggest for the JS? Any library or pure JS?

**Comment by zelark** [comment]
Sounds good.

I would suggest clipboardjs. There is a wrapper for ClojureScript, you can find it [here](https://github.com/cljsjs/packages/tree/master/clipboard).

**Comment by zelark** [comment]
@hrithik-jha, how are things going? if you need any help just create a PR.

**Comment by hrithik-jha** [comment]
Okay, will do that

**Comment by hrithik-jha** [comment]
I made a PR, let me know the changes required. I haven't implemented ClojureScript yet, still trying.

**Comment by zelark** [comment]
**If somebody also wants to take this issue, you're welcome.**

**Comment by zelark** [comment]
In the [copy-btn branch](https://github.com/zelark/nano-id-cc/tree/copy-btn) I added [the button](https://github.com/zelark/nano-id-cc/compare/copy-btn), but not the logic. It can be used as a start point.

![screen shot 2018-10-16 at 13 01 26](https://user-images.githubusercontent.com/2854582/47010067-b3d81980-d146-11e8-99a1-bb8a0a0f5ded.png)
