### ISSUE TITLE
Compress CSS

### ISSUE THREAD

**Issue by ai** [zelark/nano-id-cc#8]
We can minify CSS by csso and remove .hljs-* classes which we don’t use

`view-source:https://zelark.github.io/nano-id-cc/`

**Comment by ghost** [comment]
So, I cleaned up CSS from unneeded `.hljs-whatever` classes. Now I need to add CSSO to build process. Unfortunately, I can't just install CSSO thru Clojars - it isn't there. But I can use a plugin called `lein-npm`, which adds NPM support to Leiningen.

**Comment by ghost** [comment]
We can even use PostCSS to do CSS stuff, but CSSO should be enough for this project.

**Comment by ai** [comment]
We can use `cssnano` or any other CSS minifier

**Comment by zelark** [comment]
Sorry guys for a little delay.

> We can use cssnano or any other CSS minifier

Yep, agree. We need something tiny.

I think there is a ClojureScript tool for that task. I'll check  it on the weekend.

**Comment by zelark** [comment]
> and remove .hljs-* classes which we don’t use

Hmm, they're used implicitly by highlight.js. A serialized light theme which I choosed is little different from default one, that why I put the classes in `style.css`.

UPD: sorry, a little misunderstanding, I got it. (-:

**Comment by zelark** [comment]
@mishaor, may you create a PR with cleaned CSS?

**Comment by zelark** [comment]
Within CLJS world I found `lein-asset-minifier` plugin for CSS compression.

**Comment by ghost** [comment]
@zelark I did an initial PR: #9
